import { useLanguage } from '../contexts/LanguageContext';

export default function TermsPage() {
  const { tr } = useLanguage();
  const sections = [
    [tr('Eligibility and accounts', 'যোগ্যতা ও অ্যাকাউন্ট'), tr('You must be legally able to enter into transactions under applicable law. You are responsible for keeping your account credentials secure. We may restrict accounts involved in fraudulent, abusive or unlawful activity.', 'প্রযোজ্য আইন অনুযায়ী বৈধ লেনদেন করার সক্ষমতা থাকতে হবে। আপনার অ্যাকাউন্টের লগইন তথ্য নিরাপদ রাখা আপনার দায়িত্ব। প্রতারণামূলক, অপব্যবহারমূলক বা বেআইনি কার্যক্রমে জড়িত অ্যাকাউন্ট সীমিত করা হতে পারে।')],
    [tr('Product information', 'পণ্যের তথ্য'), tr('We work to keep product names, images, descriptions, prices and stock information accurate. Packaging, availability or supplier changes may create reasonable differences, and information may be corrected when necessary.', 'পণ্যের নাম, ছবি, বিবরণ, মূল্য ও স্টক যথাসম্ভব নির্ভুল রাখার চেষ্টা করা হয়। প্যাকেজিং, সরবরাহ বা প্রস্তুতকারকের পরিবর্তনের কারণে কিছু পার্থক্য হতে পারে এবং প্রয়োজন হলে তথ্য সংশোধন করা হতে পারে।')],
    [tr('Pricing and payment', 'মূল্য ও পেমেন্ট'), tr('Prices are shown in Bangladeshi Taka (BDT) unless stated otherwise. Available payment methods may include Cash on Delivery and supported digital payment options. Orders may be held or cancelled if payment cannot be verified.', 'অন্যভাবে উল্লেখ না থাকলে মূল্য বাংলাদেশি টাকা (BDT)-তে দেখানো হবে। প্রাপ্যতা অনুযায়ী Cash on Delivery এবং সমর্থিত ডিজিটাল পেমেন্ট ব্যবহার করা যাবে। পেমেন্ট যাচাই না হলে অর্ডার স্থগিত বা বাতিল হতে পারে।')],
    [tr('Orders and cancellation', 'অর্ডার ও বাতিল'), tr('An order is subject to stock, price, payment and delivery availability. We may cancel an order for genuine availability, pricing, fraud-prevention or operational reasons. Customers may request cancellation before dispatch, subject to the order status.', 'অর্ডার স্টক, মূল্য, পেমেন্ট ও ডেলিভারি সক্ষমতার উপর নির্ভরশীল। পণ্য অনুপলব্ধতা, মূল্যগত ভুল, প্রতারণা প্রতিরোধ বা যৌক্তিক পরিচালনাগত কারণে অর্ডার বাতিল হতে পারে। ডিসপ্যাচের আগে অর্ডারের অবস্থার ভিত্তিতে বাতিলের অনুরোধ করা যাবে।')],
    [tr('Delivery', 'ডেলিভারি'), tr('Delivery time depends on location, stock, weather, traffic and logistics. Estimated times are not guaranteed. Customers are responsible for providing a reachable phone number and accurate delivery address.', 'ডেলিভারি সময় স্থান, স্টক, আবহাওয়া, ট্রাফিক ও লজিস্টিকসের উপর নির্ভর করে। আনুমানিক সময় নিশ্চিত সময় নয়। সঠিক ফোন নম্বর ও পূর্ণ ডেলিভারি ঠিকানা দেওয়া গ্রাহকের দায়িত্ব।')],
    [tr('Returns and refunds', 'রিটার্ন ও রিফান্ড'), tr('If you receive a wrong, damaged or defective product, contact us as soon as reasonably possible. Eligibility for return, replacement or refund depends on the product type, condition and verification. Opened, used or perishable goods may not be returnable unless there is a verified defect or incorrect delivery.', 'ভুল, ক্ষতিগ্রস্ত বা ত্রুটিপূর্ণ পণ্য পেলে যত দ্রুত সম্ভব আমাদের জানান। পণ্যের ধরন, অবস্থা ও যাচাইয়ের ভিত্তিতে রিটার্ন, রিপ্লেসমেন্ট বা রিফান্ড নির্ধারণ করা হবে। যাচাইযোগ্য ত্রুটি বা ভুল ডেলিভারি ছাড়া খোলা, ব্যবহৃত বা দ্রুত নষ্ট হয় এমন পণ্য রিটার্নযোগ্য নাও হতে পারে।')],
    [tr('Acceptable use', 'ওয়েবসাইটের গ্রহণযোগ্য ব্যবহার'), tr('You may not misuse the website, attempt unauthorized access, disrupt services, abuse other users, or use the platform for unlawful or fraudulent activity.', 'ওয়েবসাইটের অপব্যবহার, অননুমোদিত প্রবেশ, সেবা ব্যাহত করা, অন্য ব্যবহারকারীকে হয়রানি করা বা বেআইনি/প্রতারণামূলক কাজে প্ল্যাটফর্ম ব্যবহার করা যাবে না।')],
    [tr('Intellectual property', 'মেধাস্বত্ব'), tr('Hadia Mart branding, original design, text, graphics and other owned content may be protected by applicable intellectual-property law. Unauthorized commercial use is not permitted.', 'Hadia Mart-এর ব্র্যান্ডিং, নিজস্ব ডিজাইন, লেখা, গ্রাফিক্স ও অন্যান্য মালিকানাধীন কনটেন্ট প্রযোজ্য মেধাস্বত্ব আইনের অধীনে সুরক্ষিত হতে পারে। অনুমতি ছাড়া বাণিজ্যিক ব্যবহার করা যাবে না।')],
    [tr('Limitation of liability', 'দায়বদ্ধতার সীমা'), tr('To the extent permitted by law, Hadia Mart is not responsible for indirect or consequential losses arising from use of the website or products. Any valid product-related liability may be limited to the amount paid for the relevant order or item.', 'আইন দ্বারা অনুমোদিত সীমার মধ্যে, ওয়েবসাইট বা পণ্য ব্যবহারের ফলে সৃষ্ট পরোক্ষ বা আনুষঙ্গিক ক্ষতির জন্য Hadia Mart-এর দায় সীমিত থাকবে। কোনো বৈধ পণ্য-সংক্রান্ত দাবিতে দায় সংশ্লিষ্ট অর্ডার বা পণ্যের পরিশোধিত অর্থের সীমার মধ্যে থাকতে পারে।')],
    [tr('Force majeure', 'নিয়ন্ত্রণের বাইরে থাকা পরিস্থিতি'), tr('Service may be delayed or interrupted by events beyond reasonable control, including natural disasters, public disruptions, strikes, infrastructure failures or supply-chain interruptions.', 'প্রাকৃতিক দুর্যোগ, জনজীবনের বিঘ্ন, ধর্মঘট, অবকাঠামোগত ব্যর্থতা বা সরবরাহ ব্যবস্থার সমস্যার মতো নিয়ন্ত্রণের বাইরে থাকা ঘটনায় সেবা বিলম্বিত বা ব্যাহত হতে পারে।')],
    [tr('Governing law and changes', 'প্রযোজ্য আইন ও পরিবর্তন'), tr('These terms are governed by applicable laws and regulations of Bangladesh. We may update these terms when services, business practices or legal requirements change. The latest version posted on the website will apply from its stated effective date.', 'এই শর্তাবলী বাংলাদেশের প্রযোজ্য আইন ও বিধিমালার আলোকে পরিচালিত হবে। সেবা, ব্যবসায়িক কার্যক্রম বা আইনগত প্রয়োজন পরিবর্তিত হলে শর্তাবলী হালনাগাদ করা হতে পারে। ওয়েবসাইটে প্রকাশিত সর্বশেষ সংস্করণ কার্যকর হবে।')],
  ] as const;

  return (
    <div className="page-shell max-w-5xl">
      <article className="rounded-3xl border border-white bg-white p-5 shadow-[0_24px_70px_-38px_rgba(10,63,42,0.35)] sm:p-8 md:p-10">
        <p className="text-xs font-bold uppercase tracking-[0.18em] text-primary-600">Hadia Mart</p>
        <h1 className="mt-2 font-display text-3xl font-extrabold text-gray-950 sm:text-4xl">{tr('Terms & Conditions', 'শর্তাবলী')}</h1>
        <p className="mt-2 text-sm text-gray-500">{tr('Last updated: 20 September 2026', 'সর্বশেষ হালনাগাদ: ২০ সেপ্টেম্বর ২০২৬')}</p>
        <p className="mt-7 leading-8 text-gray-700">{tr('By accessing or using Hadia Mart, you agree to these Terms & Conditions. If you do not agree with a term, please do not use the related service.', 'Hadia Mart ব্যবহার করার মাধ্যমে আপনি এই শর্তাবলীর সাথে সম্মত হচ্ছেন। কোনো শর্তের সাথে একমত না হলে সংশ্লিষ্ট সেবা ব্যবহার করবেন না।')}</p>
        <div className="mt-8 space-y-8">
          {sections.map(([title, body]) => <section key={title}><h2 className="text-lg font-bold text-gray-900">{title}</h2><p className="mt-2 leading-8 text-gray-700">{body}</p></section>)}
        </div>
      </article>
    </div>
  );
}
